version: '2'
services:
  mosquitto1:
    build: ./mosquitto-node
    # image: local/alpine-mosquitto:latest
    hostname: mosquitto1
    environment:
      - MOSQUITTO_BRIDGE_NODES=bridge1:1883
      - MOSQUITTO_OTHER_BROKERS=mosquitto2
  
  mosquitto2:
    build: ./mosquitto-node
    # image: local/alpine-mosquitto:latest
    hostname: mosquitto2
    environment:
      - MOSQUITTO_BRIDGE_NODES=bridge1:1883
      - MOSQUITTO_OTHER_BROKERS=mosquitto1

  bridge1:
    build: ./bridge-node
    hostname: bridge1
    environment:
      - MOSQUITTO_BROKERS=mosquitto1 mosquitto2

networks:
  default:
    external:
      name: atlas